# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  app: 'iss-microservices-poc-pricing-app'
  image: '$(dockerNamespace)/iss-microservices-poc-pricing-app'
  tag: '$(build.buildId)'

steps:
- script: cd InsuranceSalesSystem
  displayName: change workdir
- script: docker login -u $(dockerId) -p $(dockerPass)
  displayName: 'docker login'
- script: docker build -f PricingService.Web/Dockerfile -t $(image) .
  displayName: 'docker build $(app)'
- script: docker tag $(image) $(image):$(tag)
  displayName: 'docker tag $(image):$(tag)'
- script: docker push $(image):$(tag)
  displayName: 'docker push $(image):$(tag)'
- script: docker push $(image):latest
  displayName: 'docker push $(image):latest'
