# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'altkomtest/iss-microservices-poc-pricing-app:$(build.buildId)'

steps:
- script: cd InsuranceSalesSystem
  displayName: change root dir
- script: docker-compose up
  displayName: 'docker build'
