version: '3'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Pass@word1
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
  pricingservice.web:
    image: pricingservice.web
    build:
      context: .
      dockerfile: PricingService.Web/Dockerfile
    depends_on:
      - sql.data
