version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    networks:
      - docker-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - docker-network

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
   networks:
      - docker-network

  kibana:
   image: docker.elastic.co/kibana/kibana:7.4.2
   depends_on:
      - elasticsearch
   networks:
      - docker-network

  pricingservice.web:
    image: pricingservice.web
    build:
      context: .
      dockerfile: PricingService.Web/Dockerfile
    depends_on:
      - sql.data
    networks:
      - docker-network
  
  policyservice.web:
    image: policyservice.web
    build:
      context: .
      dockerfile: PolicyService.Web/Dockerfile
    depends_on:
      - pricingservice.web
      - sql.data
      - rabbitmq
    networks:
      - docker-network

  paymentservice.web:
    image: paymentservice.web
    build:
      context: .
      dockerfile: PaymentService.Web/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data: