version: '3.4'

services:
  sql.data:
    container_name: sql
    image: microsoft/mssql-server-linux:2017-latest
    networks:
      - docker-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    networks:
      - docker-network

  elasticsearch:
   container_name: es
   image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
   networks:
      - docker-network

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.4.2
   depends_on:
      - elasticsearch
   networks:
      - docker-network
  
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.4.2
    command: logstash -f /usr/share/logstash/logstash/logstash.conf
    volumes:
      - ./Logstash/logstash.conf:/usr/share/logstash/logstash/logstash.conf:ro
    depends_on:
      - elasticsearch
    networks:
      - docker-network

  pricingservice.web:
    container_name: pricing
    image: pricingservice.web
    build:
      context: .
      dockerfile: PricingService.Web/Dockerfile
    depends_on:
      - sql.data
    networks:
      - docker-network
  
  policyservice.web:
    container_name: policy
    image: policyservice.web
    build:
      context: .
      dockerfile: PolicyService.Web/Dockerfile
    depends_on:
      - pricingservice.web
      - sql.data
      - rabbitmq
    networks:
      - docker-network

  paymentservice.web:
    container_name: payment
    image: paymentservice.web
    build:
      context: .
      dockerfile: PaymentService.Web/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data: