version: '3'

services:
  pricingservice.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  policyservice.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  paymentservice.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

