// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Bo.Infrastructure.Database;

namespace PaymentService.Bo.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20181115093928_CreatePaymentDB")]
    partial class CreatePaymentDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentService.Bo.Domain.AccountOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("EffectiveDate");

                    b.Property<int?>("PolicyAccountId");

                    b.Property<DateTime>("RegistrationDate");

                    b.HasKey("Id");

                    b.HasIndex("PolicyAccountId");

                    b.ToTable("AccountOperation");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AccountOperation");
                });

            modelBuilder.Entity("PaymentService.Bo.Domain.PolicyAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("PolicyAccount");
                });

            modelBuilder.Entity("PaymentService.Bo.Domain.ExpectedPayment", b =>
                {
                    b.HasBaseType("PaymentService.Bo.Domain.AccountOperation");


                    b.ToTable("ExpectedPayment");

                    b.HasDiscriminator().HasValue("ExpectedPayment");
                });

            modelBuilder.Entity("PaymentService.Bo.Domain.Refund", b =>
                {
                    b.HasBaseType("PaymentService.Bo.Domain.AccountOperation");


                    b.ToTable("Refund");

                    b.HasDiscriminator().HasValue("Refund");
                });

            modelBuilder.Entity("PaymentService.Bo.Domain.RegisteredPayment", b =>
                {
                    b.HasBaseType("PaymentService.Bo.Domain.AccountOperation");


                    b.ToTable("RegisteredPayment");

                    b.HasDiscriminator().HasValue("RegisteredPayment");
                });

            modelBuilder.Entity("PaymentService.Bo.Domain.AccountOperation", b =>
                {
                    b.HasOne("PaymentService.Bo.Domain.PolicyAccount")
                        .WithMany("AccountOperations")
                        .HasForeignKey("PolicyAccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
